/* 
 * order-management-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateOrderItemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateOrderItemDtoTests
    {
        // TODO uncomment below to declare an instance variable for UpdateOrderItemDto
        //private UpdateOrderItemDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateOrderItemDto
            //instance = new UpdateOrderItemDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateOrderItemDto
        /// </summary>
        [Test]
        public void UpdateOrderItemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateOrderItemDto
            //Assert.IsInstanceOfType<UpdateOrderItemDto> (instance, "variable 'instance' is a UpdateOrderItemDto");
        }


        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Test]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
