/* 
 * order-management-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateOrderDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateOrderDtoTests
    {
        // TODO uncomment below to declare an instance variable for UpdateOrderDto
        //private UpdateOrderDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateOrderDto
            //instance = new UpdateOrderDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateOrderDto
        /// </summary>
        [Test]
        public void UpdateOrderDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateOrderDto
            //Assert.IsInstanceOfType<UpdateOrderDto> (instance, "variable 'instance' is a UpdateOrderDto");
        }


        /// <summary>
        /// Test the property 'ShippingAddress'
        /// </summary>
        [Test]
        public void ShippingAddressTest()
        {
            // TODO unit test for the property 'ShippingAddress'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Test]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'OrderItems'
        /// </summary>
        [Test]
        public void OrderItemsTest()
        {
            // TODO unit test for the property 'OrderItems'
        }

    }

}
