/* 
 * order-management-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrdersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrdersApiTests
    {
        private OrdersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrdersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrdersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrdersApi
            //Assert.IsInstanceOfType(typeof(OrdersApi), instance, "instance is a OrdersApi");
        }

        /// <summary>
        /// Test ApiOrdersGet
        /// </summary>
        [Test]
        public void ApiOrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiOrdersGet();
            //Assert.IsInstanceOf<List<OrderDto>> (response, "response is List<OrderDto>");
        }
        /// <summary>
        /// Test ApiOrdersIdDelete
        /// </summary>
        [Test]
        public void ApiOrdersIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiOrdersIdDelete(id);
            
        }
        /// <summary>
        /// Test ApiOrdersIdGet
        /// </summary>
        [Test]
        public void ApiOrdersIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiOrdersIdGet(id);
            //Assert.IsInstanceOf<OrderDto> (response, "response is OrderDto");
        }
        /// <summary>
        /// Test ApiOrdersIdPut
        /// </summary>
        [Test]
        public void ApiOrdersIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //UpdateOrderDto body = null;
            //var response = instance.ApiOrdersIdPut(id, body);
            //Assert.IsInstanceOf<OrderDto> (response, "response is OrderDto");
        }
        /// <summary>
        /// Test ApiOrdersIdStatusPatch
        /// </summary>
        [Test]
        public void ApiOrdersIdStatusPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //UpdateOrderStatusDto body = null;
            //var response = instance.ApiOrdersIdStatusPatch(id, body);
            //Assert.IsInstanceOf<OrderDto> (response, "response is OrderDto");
        }
        /// <summary>
        /// Test ApiOrdersPost
        /// </summary>
        [Test]
        public void ApiOrdersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateOrderDto body = null;
            //var response = instance.ApiOrdersPost(body);
            //Assert.IsInstanceOf<OrderDto> (response, "response is OrderDto");
        }
        /// <summary>
        /// Test ApiOrdersStatusStatusGet
        /// </summary>
        [Test]
        public void ApiOrdersStatusStatusGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string status = null;
            //var response = instance.ApiOrdersStatusStatusGet(status);
            //Assert.IsInstanceOf<List<OrderDto>> (response, "response is List<OrderDto>");
        }
    }

}
